// Generated by CoffeeScript 1.4.0
var Achivname, MongoConnect, config, db;

config = require('../configs/config.js');

db = '';

MongoConnect = function() {
  var db_connector, mongodb, mongoserver;
  mongodb = require('mongodb');
  mongoserver = new mongodb.Server(config.mongo.host, config.mongo.port, config.mongo.server_config);
  db_connector = new mongodb.Db(config.mongo.db, mongoserver, config.mongo.connector_config);
  return db_connector.open(function(err, dbs) {
    return db = dbs;
  });
};

MongoConnect();

Achivname = function(cb) {
  var _this = this;
  return db.collection('achievements', function(err, collection) {
    return collection.find({
      $where: "this.description.length < 1"
    }, {
      aid: 1,
      name: 1,
      _id: 0,
      description: 1,
      service: 1
    }).toArray(function(err, doc) {
      return cb(doc);
    });
  });
};

exports.main = function(req, res) {
  if (req.session.auth && req.session.auth === false) {
    return res.render('offer.ect', {
      title: 'Акция',
      session: req.session,
      message: 'Простите, но принимать участие в акциях могут только зарегистрированные пользователи.'
    });
  } else {
    if (req.body.aid && req.body.name) {
      return db.collection('offers', function(err, collection) {
        return collection.insert({
          uid: req.session.uid,
          aid: req.body.aid,
          name: req.body.name
        }, function(err, doc) {
          return res.render('offer.ect', {
            title: 'Акция',
            session: req.session,
            message: 'Спасибо за ваш вариант'
          });
        });
      });
    } else {
      return Achivname(function(achiv_list) {
        return res.render('offer.ect', {
          title: 'Акция',
          session: req.session,
          achiv_list: achiv_list
        });
      });
    }
  }
};
